name: Add Comment to Asana Task
on: push
jobs:
  add_comment:
    runs-on: ubuntu-latest
    
    steps:
    - name: Add Comment to Asana Task
      run: |
        message=$(jq -r '.head_commit.message' $GITHUB_EVENT_PATH)
        curl -X POST https://app.asana.com/api/1.0/tasks/1203924242984070/stories \
        -H "Authorization: Bearer 1/1199000149941292:38271509b013c7089be09bc0e2f4644c" \
        -H "Content-Type: application/json" \
        -d '{
          "data": {
            "text": "Commit message: " + $message
          }
        }'
